### ISSUE TITLE
Normal .Net Nuget Package requires an assembly from .Net core

### ISSUE THREAD

**Issue by roy-t** [DesignEngrLab/MIConvexHull#9]
I have a normal C#/.Net 4.6.1 project.  If I install NuGet package 1.1.16.905 everything works fine. If I install Nuget package 1.1.17.214 I get the error message that I've pasted at the bottom whenever I use anything from the MIConvexHull package.

It seems you've accidentally added a dependency to a .net core version of the assembly `System.Runtime` to the normal .Net package. I've tried to look around if I could solve the problem for you, but I don't see any .nuspec files in the repository.

  ```
System.IO.FileNotFoundException was unhandled
  FileName=System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  FusionLog==== Pre-bind state information ===
LOG: DisplayName = System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///D:/Projects/C#/TexMorph/TexMorph/bin/Debug/
LOG: Initial PrivatePath = NULL
Calling assembly : MIConvexHull.NET Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: D:\Projects\C#\TexMorph\TexMorph\bin\Debug\TexMorph.vshost.exe.config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: Attempting download of new URL file:///D:/Projects/C#/TexMorph/TexMorph/bin/Debug/System.Runtime.DLL.
LOG: Attempting download of new URL file:///D:/Projects/C#/TexMorph/TexMorph/bin/Debug/System.Runtime/System.Runtime.DLL.
LOG: Attempting download of new URL file:///D:/Projects/C#/TexMorph/TexMorph/bin/Debug/System.Runtime.EXE.
LOG: Attempting download of new URL file:///D:/Projects/C#/TexMorph/TexMorph/bin/Debug/System.Runtime/System.Runtime.EXE.


HResult=-2147024894
  Message=Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
  Source=TexMorph.Viewer
  StackTrace:
       at TexMorph.Viewer.Layers.DeformationMesh.Triangulate(IList`1 vertices)
       at TexMorph.Viewer.Layers.DeformationMesh.Render(Vector2 bottomLeft, Vector2 topRight) in D:\Projects\C#\TexMorph\TexMorph.Viewer\Layers\DeformationMesh.cs:line 56
       at TexMorph.Viewer.Layers.LayerBatcher.Draw(OrthographicCamera camera) in D:\Projects\C#\TexMorph\TexMorph.Viewer\Layers\LayerBatcher.cs:line 55
       at TexMorph.Viewer.RenderLoop.Draw(GameTime gameTime) in D:\Projects\C#\TexMorph\TexMorph.Viewer\RenderLoop.cs:line 64
       at MonoGame.Framework.WpfInterop.WpfGame.Render(GameTime time)
       at MonoGame.Framework.WpfInterop.D3D11Host.OnRendering(Object sender, EventArgs eventArgs)
       at System.EventHandler.Invoke(Object sender, EventArgs e)
       at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
       at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.DispatcherOperation.InvokeImpl()
       at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
       at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Windows.Threading.DispatcherOperation.Invoke()
       at System.Windows.Threading.Dispatcher.ProcessQueue()
       at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
       at System.Windows.Application.RunDispatcher(Object ignore)
       at System.Windows.Application.RunInternal(Window window)
       at System.Windows.Application.Run(Window window)
       at System.Windows.Application.Run()
       at TexMorph.App.Main()
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

```

**Comment by roy-t** [comment]
I no longer have this issue with the latest nuget package :).
